# caddy-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
  labels:
    app: caddy-ingress
spec:
  selector:
    app: caddy-ingress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer