FROM python:3.12.4-alpine

WORKDIR /app

COPY ai-assistant/dashboard-backend/app/pyproject.toml ./
COPY ai-assistant/dashboard-backend/app/poetry.lock ./

RUN pip install poetry==1.8.3 && poetry config virtualenvs.create false && poetry install --no-root
RUN apk update
RUN apk add vim

COPY ai-assistant/dashboard-backend/app/app ./app
COPY ai-assistant/dashboard-backend/app/api ./api
COPY ai-assistant/dashboard-backend/app/core ./core
COPY ai-assistant/dashboard-backend/app/database ./database
COPY ai-assistant/dashboard-backend/app/tests ./tests
COPY ai-assistant/dashboard-backend/app/alembic.ini ./
COPY ai-assistant/dashboard-backend/app/migrations ./migrations
COPY ai-assistant/dashboard-backend/app/main.py ./main.py

# Copy startup scripts from cicd repo
COPY cicd-ai-assistant/scripts/start-prod.sh ./
COPY cicd-ai-assistant/scripts/load_env.py ./

# Create log directory
RUN mkdir /log

CMD ["sh", "start-prod.sh"]